# base image
FROM node:9.11.1

# set working directory
RUN mkdir /usr/src/app
RUN mkdir /usr/src/app/node_modules
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json /usr/src/app/package.json
RUN npm i

# start app
CMD ["npm", "start"]
