# docker-compose.yml
version: '3.5'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      - ENV=development
      - PORT=4000
      - DB=mongodb://db:27017/
    volumes:
      - "./:/app"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: "db"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask

networks:
 default:
  name: flask
